[pytest]
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:sqlalchemy.*:
    ignore::DeprecationWarning:jsonschema.*:
    ignore::DeprecationWarning:connexion.*:
    ignore::DeprecationWarning:.*RefResolver.*
    ignore::DeprecationWarning:.*RefResolutionError.*
